language: node_js
sudo: false
node_js:
  - 6
  - 8
  - 10
  - 12
  - 14

os:
  - linux
  - osx
script:
  - npm test
after_success:
  - npm run codecov -- -f coverage/lcov.info

notifications:
  email: false
